services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/vagas_db
    # FUNDAMENTAL: Cria a rota para o Ollama que está fora deste Compose
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=vagas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
